### PR TITLE
Truncate restart identity postgres

### PR DESCRIPTION
**Pull request by dandoh**

### CODE REVIEW

**Comment by khaiql** [comment]
any special reason why you need this?

**Comment by dandoh** [comment]
Some legacy code have tests which insert manually-specified ID records. This some how messes up the auto counter for the IDs. New test swith auto IDs will fail because `violates unique constraint id_pkey`, thus we wish every time we clean the database it also restarts the counter.

**Comment by khaiql** [comment]
I understand your problem, however it's obviously a bad practice when hardcoding the id in your test. My suggestion is to fix your test instead of changing the library.

**Comment by dandoh** [comment]
> I understand your problem, however it's obviously a bad practice when hardcoding the id in your test. My suggestion is to fix your test instead of changing the library.

It is unfortunately. 

What about adding a new function CleanRestartIdentity()?

**Comment by khaiql** [comment]
I'm thinking the option should be generic to all drivers, not specific to postgres. So maybe you can think of an option for specifying the custom SQL command, or strategy? I'll close this first. Thanks for the contribution

**Pull request closed without merging**
